### PR TITLE
Made it work with vibe 0.8.4

### PR DESCRIPTION
**Pull request by burner**
As the Subject states it. This PR makes kafka-d work with vibe.d 0.8.4

### CODE REVIEW

**Comment by andre2007** [comment]
Thanks for taking care of this. With 2.81.1 I get this error:

C:\Develop\D\dmd2\windows\bin\..\..\src\phobos\std\variant.d(671,21): Error: cannot modify `immutable` expression `*p`
C:\Develop\D\dmd2\windows\bin\..\..\src\phobos\std\variant.d(574,17): Error: template instance `std.variant.VariantN!20LU.VariantN.opAssign!(immutable(Metadata))` error instantiating
C:\Develop\D\dmd2\windows\bin\..\..\src\phobos\std\concurrency.d(101,22):        instantiated from here: `__ctor!(immutable(Metadata))`
C:\Develop\D\dmd2\windows\bin\..\..\src\phobos\std\concurrency.d(629,23):        instantiated from here: `__ctor!(immutable(Metadata))`
C:\Develop\D\dmd2\windows\bin\..\..\src\phobos\std\concurrency.d(620,10):        instantiated from here: `_send!(immutable(Metadata))`
C:\Develop\D\dmd2\windows\bin\..\..\src\phobos\std\concurrency.d(599,10):        instantiated from here: `_send!(immutable(Metadata))`
dependencies\kafka-d\source\kafkad\connection.d(206,29):        instantiated from here: `send!(immutable(Metadata))

**Comment by burner** [comment]
I'm on linux (2.081.1) and can not reproduce this. Which test or example are you compiling?

**Comment by andre2007** [comment]
I solved this issue by deleting all cached dub packages. Maybe some of the old packages were created with an older version of dmd.

**Comment by burner** [comment]
properly an old vibe.d version in the cache

**Comment by andre2007** [comment]
@yannick Could you have a look at this pull request? Thanks a lot!

**Comment by yannick** [comment]
i dont actively use the package anymore @andre2007  so since 2 people mentioned it working i just merged it.

**Comment by andre2007** [comment]
Great, if possible, could you also create a new release, to make the new version accessible from code.dlang.org?

@burner Also thanks to you for taking care of this.

**Comment by burner** [comment]
a new release would be very nice. thank you

**Comment by yannick** [comment]
done, however i can't currently log in to code.dlang.org nor reset my pw. 
so we need to wait until it reloads

**Comment by yannick** [comment]
@burner i can move that repo to my org and give you commit access if you want?

**Comment by burner** [comment]
sounds like a plan
